### ISSUE TITLE
Windows 8.1, 0.2.4.2, "Uh-oh", consistently fails to install.

### ISSUE THREAD

**Issue by sirocyl** [riverar/uxstyle#10]
I'm having some trouble installing the uxstyle 0.2.4.2 package.

Linked: UxStyle_20150426145247_0_Installer64.log and UxStyle_20150426145247.log
https://gist.github.com/sirocyl/5f111eb9b98686f456d8

It's looking like the kernel-mode driver bit is struggling to start.
I've tried manually removing the service using `sc delete uxstyle`, which succeeds in axing the registry entry for it, and since the installer fails before installing the other service, `sc delete UnsignedThemes` fails and doesn't do anything.
I've also run the installer with the `/uninstall` switch before trying again.

I'm on a Microsoft Surface Pro 1 with Windows 8.1, latest firmware and all the latest updates, including November 2014.
I'll disable driver signature enforcement and secure boot now, to test if it succeeds then.

**Comment by riverar** [comment]
The latest compatible UxStyle for Windows 8.1 is 0.2.3.0 (see http://uxstyle.com). Can you confirm that works?

**Comment by sirocyl** [comment]
Thanks for your prompt reply!

Forgot to mention, I had tried that version, and it had a similar issue. I assumed the newer version would be more stable, so I went on with that one.

It looks like, manually deleting the service before it, the older version in fact installed, granted I have driver signature enforcement off and Secure Boot disabled now, so I'll see if it retains, and if unsigned themes work.
If anyone else is as confused as I was, just do a round of `sc delete uxstyle` and `sc delete UnsignedThemes` before retrying.

I'll close this issue now, since it was resolved.

An earlier failed install left the service entry behind, so it would fail to install that older version.
The newer version fixed the installer logic, but the kernel-mode parts seem to be incompatible, as expected, so it failed with a different error at the StartService step.

Linked: the install failure logs with 0.2.3.0.
https://gist.github.com/sirocyl/ef853afb2fb19f0692dd
The relevant log lines are below:

```
MSI (s) (8C:A4) [15:58:59:347]: Executing op: ActionStart(Name=InstallDriver_Cmd,,)
MSI (s) (8C:A4) [15:58:59:347]: Executing op: CustomActionSchedule(Action=InstallDriver_Cmd,ActionType=3073,Source=BinaryData,Target=CAQuietExec,CustomActionData="sc.exe" create uxstyle type= kernel start= auto group= "File System" binPath= C:\WINDOWS\system32\Drivers\uxstyle.sys)
MSI (s) (8C:D0) [15:58:59:347]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI3B61.tmp, Entrypoint: CAQuietExec
MSI (s) (8C:C0) [15:58:59:347]: Generating random cookie.
MSI (s) (8C:C0) [15:58:59:347]: Created Custom Action Server with PID 5580 (0x15CC).
MSI (s) (8C:F4) [15:58:59:379]: Running as a service.
MSI (s) (8C:F4) [15:58:59:379]: Hello, I'm your 32bit Elevated custom action server.
CAQuietExec:   CreateService FAILED 1073:
CAQuietExec:  
CAQuietExec:  The specified service already exists.
CAQuietExec:  
CAQuietExec:  Error 0x80070431: Command line returned an error.
CAQuietExec:  Error 0x80070431: CAQuietExec Failed
CustomAction InstallDriver_Cmd returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

For contrast, the similar log lines, except on CreateService, for the first error:

```
MSI (s) (10:24) [15:06:01:555]: Executing op: ActionStart(Name=StartDriver_Cmd,,)
MSI (s) (10:24) [15:06:01:555]: Executing op: CustomActionSchedule(Action=StartDriver_Cmd,ActionType=3073,Source=BinaryData,Target=CAQuietExec,CustomActionData="sc.exe" start uxstyle)
MSI (s) (10:04) [15:06:01:555]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI8030.tmp, Entrypoint: CAQuietExec
CAQuietExec:   StartService FAILED 31:
CAQuietExec:  
CAQuietExec:  A device attached to the system is not functioning.
CAQuietExec:  
CAQuietExec:  Error 0x8007001f: Command line returned an error.
CAQuietExec:  Error 0x8007001f: CAQuietExec Failed
CustomAction StartDriver_Cmd returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (10:24) [15:06:01:586]: Note: 1: 2265 2:  3: -2147287035 
```
