### ISSUE TITLE
Windows 10 Build 10240 Lag

### ISSUE THREAD

**Issue by Krutonium** [riverar/uxstyle#14]
Start button just goes black and the start menu lags. Otherwise works.

**Comment by riverar** [comment]
What theme are you using? This is a msstyle issue, likely not updated for the build of the OS you're using.

**Comment by Krutonium** [comment]
I tried a variety of themes.

http://carborunda.deviantart.com/art/Snowy8-for-Windows-8-8-1-409788674
http://cu88.deviantart.com/art/Ubuntu-Theme-Windows-10-Technical-Preview-486125368
http://rian76.deviantart.com/art/Tequilla-port-For-Win8-1-Beta-427055271

I would also like to mention that themes only work sometimes - UXStyle doesn't seem to always work from boot.

**Comment by riverar** [comment]
msstyles are not forward compatible. None of those msstyles say they were built for/tested on 10240.

**Comment by Krutonium** [comment]
I know that, and ignoring that, UXStyle doesn't always manage to start up with Windows.

**Comment by riverar** [comment]
So out of N reboots, it fails to start up some of the time? Does it throw an error in the eventlog documenting the service startup failure? Does starting it afterwards work?

**Comment by Krutonium** [comment]
I don't have the log anymore, and I forget... 24 days later :/
