### ISSUE TITLE
Doesn't seem to be installing on windows 10 build 10162

### ISSUE THREAD

**Issue by DrZed** [riverar/uxstyle#15]
as title says :|

**Comment by riverar** [comment]
Can you be a little more specific? Are you receiving an error?

**Comment by DrZed** [comment]
No it says done then that's it I don't see the theme listed under windows themes or anything I just want my folders to be dark :\

**Comment by DrZed** [comment]
I use the dark theme registry key for my apps and stuff http://puu.sh/ju5wm.png and I want my folders to be coloured as such I'm a programmer and I hate going from my dev enviroment to bright folders, skype, etc

**Comment by DrZed** [comment]
And don't tell me to use high contrast themes they all suck... especially since white borders around everything

**Comment by riverar** [comment]
This isn't a customization forum, it's an issue tracker for the core UxStyle software. You might have better luck with msstyle support at http://vistastylebuilder.com/forum/index.php
