### ISSUE TITLE
Can't uninstall windows 8.1 uxstyle after installing windows 10?

### ISSUE THREAD

**Issue by dragons4life** [riverar/uxstyle#16]
<img src='http://i.imgur.com/wfKKxzw.png'/>
Log File = http://pastebin.com/8XHbymQF

**Comment by instance01** [comment]
Found in the event viewer that both the UnsignedThemes and the uxstyle service failed at startup, so I decided to uninstall it as I'm not using any themes in windows 10 anymore.
Had the same issue though with the setup failing, but after running [this Fixit](http://support2.microsoft.com/default.aspx?scid=kb;en-us;290301) I could uninstall it without problems.
I also had uninstalled the services with `sc delete uxstyle` and `sc delete UnsignedThemes` beforehand and had manually removed the uxstyle.sys file from C:\Windows\System32\drivers\ and unsignedthemes.exe from C:\Windows\, so that might've helped too.

**Comment by dragons4life** [comment]
thanks

**Comment by riverar** [comment]
Can I close this issue? Or is there something you need help with?

**Comment by dragons4life** [comment]
Yeah go ahead and close it. @riverar

**Comment by ColeHardTruth** [comment]
I'm having the same issue, actually. I can neither uninstall the old Windows 8.1 uxstyle nor install the new 10 RTM uxstyle.

Uninstall using 8,1 log: http://pastebin.com/rSjFtvCN
Install using 10 log: http://pastebin.com/Wjh47fgA

I attempted using the above poster's fixit, but it doesn't exist. :(

**Comment by instance01** [comment]
@ColeHardTruth Do you still need the fix? I just looked for it and found it in my downloads folder. I probably should clean up more often >.>
Anyways here it is:
https://dl.dropboxusercontent.com/u/82137075/MicrosoftFixit.ProgramInstallUninstall.MATSKB.Run.exe

**Comment by ColeHardTruth** [comment]
I still need it, yes. But the utility is unable to detect that uxstyle can't uninstall. And I can't find the "13-digit product code" that I need to proceed after saying that it was something else that can't uninstall. Could you help me find that?

**Comment by diffficult** [comment]
also tried the fix linked and it's not working. I could manually remove the old usxstyle version but couldn't install the new one. 

here's my error log from the installer http://pastebin.com/F1anPgnY

**Comment by klepsydra** [comment]
Same problem for me. It's just jammed. Can neither uninstall nor (re)install.

In services.msc, Unsigned Themes is set to Automatic but will not Start, claiming
"Error 2: The system cannot find the file specified."

even though  C:\Windows\unsignedthemes.exe is really there and intact (unmodified version 0.2.3.0, 13824 bytes, dated 20130923)

**Comment by reckoncraft** [comment]
I also have the same problem.  The Microsoft FixIt no longer works, so I downloaded Geek Uninstaller but the problem still persists.

I might roll my computer back to Windows 8.1 just to see if I could uninstall it there but since there's no guarantee it will work, I hope that there could be a fix.

**Comment by riverar** [comment]
Don't rollback. Issue the following commands in an elevated command prompt:
`sc delete uxstyle`
`sc delete UnsignedThemes`

Then find/use the Windows Installer Cleanup Utility to remove the UxStyle entry and reinstall.

**Comment by reckoncraft** [comment]
@riverar yes, this works!  It took me quite a bit of digging around to find the Windows Installer Cleanup Utility/Microsoft Fixit though since Microsoft hasn't officially supported it for Windows 10.  To anyone else who has the problem, the link to the Fixit is http://go.microsoft.com/?linkid=9779673.

Cheers!

**Comment by DAOWAce** [comment]
Chiming in to say I had the same issue after upgrading to Windows 10.

The first time Windows booted to the desktop during the later part of the installation my screen rapidly flashed over and over, endlessly, on the logon screen.

I could only enter Windows in safe mode, which no doubt screwed up my install as I had numerous issues with a bunch of the Windows 10 ms-* stuff. (had to run some powershell command to get it fixed)

Eventually found out it was uxstyle causing issues, as reported by checking the WER archive and seeing dozens of reports for it:

> Description
> Faulting Application Path:	C:\Windows\System32\winlogon.exe
> 
> Problem signature
> Problem Event Name:	APPCRASH
> Application Name:	winlogon.exe
> Application Version:	10.0.15063.250
> Fault Module Name:	UxTheme.dll
> Fault Module Version:	10.0.15063.0

Unfortunately, it's impossible to uninstall, as it claims my theme files are modified and need to be restored.  Even taking ownership of them, moving them and replacing with the backup didn't do anything.

The links here don't seem to be relevant anymore, so for anyone currently searching, this fixit seemed to work: https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed

**Comment by ghost** [comment]
@DAOWAce thx, saved my day <3

**Comment by brian-mk** [comment]
Same problem here.
In my case I am running Win 10 1703. Update to 1709 is failing because I cannot uninstall UxStyle.
I've tried everything suggested in this thread without success.
Any help would be much appreciated.

**Comment by brian-mk** [comment]
No response.
Is the UxStyle software originator dead or unwilling respond?

**Comment by brian-mk** [comment]
To quote a software engineer I met several years ago, 'I hate computers!'.
He always said that Windows was a 'toy' operating system that ran on 'toy' computers when compared to a professional OS like Unix or Linux that understood multi-user and security issues from the very beginning.
I have to agree with him.

**Comment by DAOWAce** [comment]
@brian-mk The tool I linked hasn't worked for you?  It was the only thing that fixed the problem for me.

Check if the files are still there and take ownership/rename if so?

**Comment by brian-mk** [comment]
The tool in the link appears to change something in the registry which allows the update to 1709 to work.

However, UxStyle still appears under Control Panel->Programs and Features. The uninstaller is still in the registry under...
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\
I could simply delete the registry entry for the uninstaller manually.

There are some other UxStyle droppings left lying around in the registry. It's not obvious to me how to clean it up.

There also appears to be related files and folders under C:\Windows\Resources\Themes that are hard to delete without changing the security settings. I think you need to be TrustedInstaller.

In the absence of an uninstaller it would be useful to have some information on how to clean up the mess.
