### ISSUE TITLE
Windows 10 animations

### ISSUE THREAD

**Issue by phly95** [riverar/uxstyle#17]
Try some themes, and you'll see that animations don't work properly. Switching desktops using ctrl+win+right/left will result in no animation vs official microsoft has animation. Same goes for minimizing and closing windows.

**Comment by riverar** [comment]
Not a UxStyle issue. This is a msstyle issue, either edited incorrectly (e.g. using an old tool) or for a different version of the OS (e.g. Windows 8 msstyle).

**Comment by phly95** [comment]
So does that mean people can create their own animations if the right tools were made?

**Comment by riverar** [comment]
Yep. Might find some help at http://vistastylebuilder.com/forum/index.php
