### ISSUE TITLE
UxStyle_0241_x86_x64_rel2_preview.exe not working on Windows 10 9926 x64

### ISSUE THREAD

**Issue by daveo76** [riverar/uxstyle#2]
UxStyle_0241_x86_x64_rel2_preview.exe installs successfully. Then when I apply a theme. It causes explorer.exe to crash and restart. Then it creates a file "WER34B7.tmp.WERDataCollectionFailure.txt" and in it. It says "Heapdump not attached to report.
ProcessHeapDumpRequest failed: 0x80004005"

**Comment by riverar** [comment]
Can you provide the msstyle used? Does it crash with all msstyles?

**Comment by daveo76** [comment]
Thanks for replying back. Yes it crashes with any msstyles I use.

**Comment by nicelyjobs** [comment]
just want to remember that happens only in X64 version (W10 9926) what daveo76 saied

**Comment by tigr72** [comment]
UxStyle_0241_x86_x64_rel2_preview.exe doesn't work with windows 10 build 9926 x64 when I try to apply theme it just resets explorer and doesn't apply theme...

**Comment by Xaaeon** [comment]
Just want to confirm that UxStyle_0241_x86_x64_rel2_preview.exe does not work with Windows 10 build 9926 x64. As others have reported, regardless of msstyle used there is no change.

**Comment by riverar** [comment]
Can you upload the msstyle you're using? Is it built specifically for Windows 10? (Old msstyles are never compatible with newer operating systems.)

**Comment by Xaaeon** [comment]
I tried
http://www.deviantart.com/art/Licorice-for-Windows-10-Technical-Preview-489354532,
http://cu88.deviantart.com/art/Yosemite-Black-Theme-Windows-10-492900635,
and
http://link6155.deviantart.com/art/Silk-for-Windows-10-Technical-Preview-487071428.
They were made for Windows 10 and have worked for all the previous builds
of Windows 10.

**Comment by riverar** [comment]
Excellent, thanks. Investigating now.

**Comment by riverar** [comment]
64-bit builds work now. Look for next release.

![Screenshot of themed Windows 10 x64](https://cloud.githubusercontent.com/assets/475132/6429958/30d3a292-bfa8-11e4-927a-78783275e8a2.png)
