### ISSUE TITLE
After applying a theme for Windows 10 and logging off, explorer will no longer run on that user

### ISSUE THREAD

**Issue by dominichayesferen** [riverar/uxstyle#20]
After installing UxStyle, applying a theme for Windows 10, logging out and then logging back in again, explorer and Task Manager will NO longer run on the system. The only solution to this on my PC is to restore to a point before installing UxStyle...

**Comment by riverar** [comment]
Which theme? Was it explicitly designed for the build of Windows you're using? (Certainly a theme issue, not a UxStyle issue, but would like to try it.)

**Comment by riverar** [comment]
Closing due to age
