### ISSUE TITLE
Hasn't been updated in 9 months

### ISSUE THREAD

**Issue by phly95** [riverar/uxstyle#22]
Is this project even active anymore. It was a cool project, but if it is dead, I guess it's time to find alternatives.

**Comment by riverar** [comment]
UxStyle is a mature 6 year old solution and hadn't needed changes until recently for Threshold 2 of which I'm already working on.

Sent from my T-Mobile 4G LTE Device

**Comment by phly95** [comment]
OK, that's great news! Thanks for everything so far.
