### ISSUE TITLE
Suggestion: Patch explorerframe.dll + shell32.dll

### ISSUE THREAD

**Issue by longnguyen2004** [riverar/uxstyle#23]
Hi. I'm currently using Windows 10 build 1511. I notice that some themes can change the Explorer + Start menu BG. After a little research i found out that explorerframe.dll and shell32.dll need to be patched. Can you find out how to patch those files?

**Comment by longnguyen2004** [comment]
no one answer?

**Comment by joserebelo** [comment]
That's not the purpose of uxstyle, the dlls just need the resources changed. There are many tools that allow you to patch those dlls easily.

**Comment by riverar** [comment]
Find your nearest customization community and they can help you. If you use Style Builder, you can try http://vistastylebuilder.com/forum/
