### ISSUE TITLE
Not applying correctly on Windows 10

### ISSUE THREAD

**Issue by psydex** [riverar/uxstyle#25]
I just installed UxStyle, placed theme in Resources/Themes, applied but nothing changed beside few minor colors changes. Service is running - I checked. What am I doing wrong?

Demonstration: https://gfycat.com/PleasedImmaterialFulmar

**Comment by CHEF-KOCH** [comment]
You need to write down which version you exactly use (cmd -> winver) because in newer previews it may not work anymore and needs to be fixed.

**Comment by psydex** [comment]
`Version 1511 (OS Build 10586.318)`

**Comment by CHEF-KOCH** [comment]
Then this ticket is a duplicate of #21. Try this [workaround](https://github.com/riverar/uxstyle/issues/21#issuecomment-218798946).

**Comment by riverar** [comment]
Is this a fresh Windows install?

**Comment by riverar** [comment]
Closing due to age, file a new issue if needed.
