### ISSUE TITLE
Themes malfunctioning on resuming from standby or signing in

### ISSUE THREAD

**Issue by MacgyverJohnson** [riverar/uxstyle#26]
Thanks @riverar  for the this really cool software for applying the world of 3rd party themes :+1:  :100: 

Using Windows 8.1 x64 6.3 build 9600 ....UxStyle Community Edition 0.2.4.2 with is used by [Uxtheme Multi Patcher](http://www.windowsxlive.net/uxtheme-multi-patcher/)....Part of some themes are not working properly when resumed from standby(sleep) on resigning in (press Win+L to lock) restarting DWM, explorer, nothing working but if i go to personalisation i see curently active theme is unsaved theme( which implies some personalization settings was changes without user interaction) reapplying the theme works but i enter sleep and resume  several times a day and its not productive to be able to apply theme repeatedly.....Bellow some screenshots 
**# Theme applied before stanby**
![screenshot 209](https://cloud.githubusercontent.com/assets/17729946/16150700/787ab832-34ba-11e6-9492-1130a197b98d.png)
![screenshot 210](https://cloud.githubusercontent.com/assets/17729946/16150732/b36ba9d8-34ba-11e6-88a3-4c74f37ce5c3.png)
![screenshot 197](https://cloud.githubusercontent.com/assets/17729946/16150772/038d7a7c-34bb-11e6-8c31-9ccf327b0c6f.png)
![screenshot 196](https://cloud.githubusercontent.com/assets/17729946/16150773/038e0ef6-34bb-11e6-9fb9-0fb915ea5063.png)
![screenshot 194](https://cloud.githubusercontent.com/assets/17729946/16150771/038860be-34bb-11e6-9543-152790fc33eb.png)

**# Theme background malfunction after resuming from stanby**
![screenshot 207](https://cloud.githubusercontent.com/assets/17729946/16150836/7a3cab66-34bb-11e6-8878-5d8a23343487.png)
![Uploading Screenshot (206).png…]()
![screenshot 205](https://cloud.githubusercontent.com/assets/17729946/16150839/7a4d070e-34bb-11e6-9bff-7d1fd1f08ec3.png)
![screenshot 204](https://cloud.githubusercontent.com/assets/17729946/16150837/7a4ae3ac-34bb-11e6-85de-95856d29da07.png)
![screenshot 208](https://cloud.githubusercontent.com/assets/17729946/16150838/7a4ccc8a-34bb-11e6-9fae-837cec0ae168.png)

All of these software(7zip file manager,Void tools search engine, PDF-Xchange Viewer) uses windows colour scheme....they are affected howerer my windows file explorer is not affected......pls help me out?
I have installed a fresh windows 8.1 Pro in virtual box and have patched it using Uxtheme Multi Patcher and same prob there
Thanks in advanced :)

**Comment by MacgyverJohnson** [comment]
Found solutions from [virtualcustoms.net](http://virtualcustoms.net/showthread.php/70881-Sleep-Mode-change-colorshttp://virtualcustoms.net/showthread.php/70881-Sleep-Mode-change-colors) 
Thanks a lot to Mr.Grim and Dark Knight.......
I thinks its a uxstyle bug no?

**Comment by riverar** [comment]
No, it affects normal themes too. UxStyle's purpose is to just remove digital signature checks.
