### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by clembu** [riverar/uxstyle#27]
Hello

I find it unclear how to install this software.
Do I need to build the thing using the instructions in the readme and then run the installer that I built?
In that case, how do I "sign" the code? Do I really need to submit the built executable to the MS Dev portal (I'm running Windows TH2 (1511) ), or is a "test-signing" enough?

Or is there a hidden installer that will magically set up the thing?

**Comment by clembu** [comment]
Well maybe you should just look at the release tab?

**Comment by blackcrack** [comment]
![GitHub Logo](http://blackysgate.de/files/folder-root/smilys/gif/popcorn.gif)
