### ISSUE TITLE
installswitches for unattended / silentinstall

### ISSUE THREAD

**Issue by blackcrack** [riverar/uxstyle#28]
This is a very nice program, but it need 
silent install switches :)

Thank you very much for this 
nice program !

by the way
your program it's in different computers news there in Germany !
keep it up !

best regards
blacky

blackysgate.de

**Comment by riverar** [comment]
If you pass /? into the installer, you'll be pointed to http://uxstyle.com/support/install-switches/

> /install | /uninstall /layout [directory] - installs, uninstalls or creates a complete local copy of the bundle in directory. Install is the default.
> /passive | /quiet - displays minimal UI with no prompts or displays no UI and no prompts. By default UI and all prompts are displayed.
> /log log.txt - logs to a specific file. By default a log file is created in %TEMP%.

**Comment by blackcrack** [comment]
oh slap me.. i was lazy ..
i did think its give not switches....
now, well, thank you very much :)
( by the way, it is this not your page ? 
http://www.windowsxlive.net/uxtheme-multi-patcher/ 
)
best regards
Blacky
