### ISSUE TITLE
Prevents Windows 10 Anniversary Update from installing

### ISSUE THREAD

**Issue by Aluminite** [riverar/uxstyle#30]
I tried installing the anniversary update today, only for it to fail. THREE TIMES. When I uninstalled UxStyle, everything worked fine.

**Comment by riverar** [comment]
Did it fail with an error that you can provide?

**Comment by yuukiw** [comment]
hmm if i remember right my prior instal had issue installing the update to but i never linked it to UXStyle or any thing like that.

**Comment by Aluminite** [comment]
It just says "Restoring your previous version of Windows..." about halfway through the update.

**Comment by riverar** [comment]
Closing due to age, file a new issue if needed.
