### ISSUE TITLE
Result in messed up Explorer links in newest windows 10 version. 

### ISSUE THREAD

**Issue by yuukiw** [riverar/uxstyle#32]
After using uxstyle and any theme windows 10 basicly becimes use less sinxe it either softlocks in the log in screen or the Explorer constantly crashes.

**Comment by riverar** [comment]
This is not a UxStyle issue. This is an issue with the theme you applied -- probably not matching the build of Windows you're using.

**Comment by yuukiw** [comment]
Are you sure about this? 
The the themes worked flawless before i did a clean install on Windows. The windows version before hand was one behind but that is it. The themes itself work Minus most visual Tweaks until uxstyle is applied. 

On the other Hand it isnt really that the links are Messe up it's more that he has some Kind of Problem with displaying win 10 apps.  They either dont open or open to to an balckish screen. 

One thing i also noticed is that the change to an 3rd party theme doesnt seem to Bode well with the gpu driver since he seemingly keeps crashing.

**Comment by riverar** [comment]
Can you provide a link to the msstyle in question?

**Comment by yuukiw** [comment]
https://drive.google.com/file/d/0B94u0_R6vixWV0szeXJkc05HWEU/view?usp=sharing

**Comment by yuukiw** [comment]
i also installed a old GPU Driver but that doesnt seem to work either.

**Comment by riverar** [comment]
Uninstall UxStyle, reboot, then try http://www.windowsxlive.net/uxtheme-multi-patcher/. Suspect you'll see the same results, confirming it's a theme issue.

**Comment by riverar** [comment]
Uninstall UxStyle, reboot, then try https://www.syssel.net/hoefs/software_uxtheme.php?lang=en. Suspect you'll see the same results, confirming it's a theme issue.

**Comment by yuukiw** [comment]
Hmm, you program says installed the program you linkes says unpatched. Is this supposed to happen?
I also tried to replace the new OS Files with the files from an fairly recent backup of my Win 10 pre fresh install. Not even those for sure patched files changed anything on the issue. (Uxtheme,uxinit and themeui.dll i mean)

**Comment by riverar** [comment]
The program I linked to alters files on disk, UxStyle does so in memory -- different technology. Make sure you remove or disable UxStyle before patching the on-disk files.

**Comment by yuukiw** [comment]
hmm yeah it seems Theme Related even one that worked without a problem for sure doesnt work now. I guess Windows did change something. 
Either that or Windows doesnt like being on Sataport 2....

Edit:
since switching back to on of the default themes and reloging fixes everything.

**Comment by yuukiw** [comment]
The evenloger says that Microsoft.Windows.Cortana_cw5n1h2txyewy!CortanaUI and Microsoft-Windows-Immersive-Shell keep crashing and will be deactivated and the notify center says that the Display Driver is crashing and that it will switch to the basic driver.

Just if anyone else has an similar problem.

**Comment by yuukiw** [comment]
anyways thanks you trying to help.
