### ISSUE TITLE
No longer working on Windows 10 Anniversary Update

### ISSUE THREAD

**Issue by antidotcb** [riverar/uxstyle#33]

**Comment by N1h1l1sT** [comment]
I should also mention that not only does THIS no LONGER work on Windows 10 Anniversary Update, but nor does Mr.Grim's method without patching any files (http://virtualcustoms.net/showthread.php/70555-Uxstyle-and-Theme-Signature-Bypass-for-Windows-10-TH2-AKA-1511-AKA-10586)

This should be corroborated by more people to assure that it isn't a localised problem on my part, but I thought it's worth mentioning

**Comment by riverar** [comment]
Is this a fresh Windows install?

**Comment by N1h1l1sT** [comment]
Not exactly, no.

I installed windows on 24/04/2016, updated them and installed all the latest drivers from Alienware's Website
I then installed lots of heavy programmes, and really heave ones (Visual Studio, Microsoft SQL Server, etc)
Lastly, I installed the customisations (uxstyle, DisplayFusion, WindowsFX, ObjectDock, Fences, Tiles, StartIsBack++, OldNewExplorer, cool skin [Virtual Customs' HUD Evolution])

Everything worked great.
Days passed... weeks passed, then I turn the laptop on a few days ago and I decide to change from HUD Evolution to Jarvis skin, only to find out that I could no longer apply any skins except windows' original ones.

---

Quoting from my post on Virtual Customs:
[quote]
P.S. It happened to me when I tried to change the skin I had already applied, which could also be an indicator.
What I mean is this:
1) I had the HUD skin applied upon first installing Windows 10 Anniversary edition (everything worked like a charm)
2) Some updates got installed
3) I decided to change the skin to Jarvis
4) I found out that I couldn't anymore - nor could I go back to the HUD skin with either of the 2 methods
[/quote]

**Comment by ghost** [comment]
Have you tried uninstalling UxStyle, re installing it, and the applying the theme again? I've noticed that when switching themes, I have to do that in order for the themes to load again.  Apparently it's something I have to do every time I switch themes. If not then try these steps,

1.) attempt to switch themes (will not fully load in this step but do so anyway)
2.) uninstall uxstyle
3.) re install uxstyle
4.) attempt to apply the theme you tried in step 1

It should apply fine if you do those steps every time you attempt to switch themes

It will however load the theme as an unsaved theme but it should still load it fine if you follow all four steps in that exact order.

I'm not sure why it has this bug to be honest but the steps above work fine for me.

**Comment by N1h1l1sT** [comment]
It's fairly peculiar...
I had tried this before and nothing would work, but I gave it a try again and everything's working just fine.

I'm not sure if a windows update fixed it or just something weird was going on, but problem is solved for me after uninstalling, getting everything back to original windows standards, and then going unstyle as usual.

Thank you

**Comment by riverar** [comment]
Closing due to age, please file a new bug (or comment on an existing one) if still an issue. (Suspect it is.)
