### ISSUE TITLE
Windows 10 Anniversary Update WinLogon/DWM crash

### ISSUE THREAD

**Issue by shadeMe** [riverar/uxstyle#34]
The driver causes WinLogon.exe and DWM.exe to crash when a secondary display is attached/detached.  This causes Windows to forcefully logout of the current user session, and in some cases, prevent login until the OS is restarted. The crash offsets are always the same whenever this happens. Running Windows 10 x64. I don't recall this particular issue ever cropping up when running the previous update of Windows.

Corresponding WERs:

> Version=1
> EventType=APPCRASH
> EventTime=131169649061252623
> ReportType=2
> Consent=1
> UploadTime=131170513675914847
> ReportIdentifier=0f3ed0a3-6e0d-11e6-9c6b-d9f3f921b2ef
> IntegratorReportIdentifier=05ea4e13-8ba9-47ea-b8e7-4afb24908876
> NsAppName=winlogon.exe
> AppSessionGuid=000026f4-0003-0010-544f-0cce1902d201
> TargetAppId=W:0000f519feec486de87ed73cb92d3cac802400000000!00001478b34132fa7c0b9bb6b5947259230ccc1cc849!winlogon.exe
> TargetAppVer=2016//07//16:02:14:17!a9f9f!winlogon.exe
> BootId=4294967295
> Response.type=4
> Sig[0].Name=Application Name
> Sig[0].Value=winlogon.exe
> Sig[1].Name=Application Version
> Sig[1].Value=10.0.14393.0
> Sig[2].Name=Application Timestamp
> Sig[2].Value=57899879
> Sig[3].Name=Fault Module Name
> Sig[3].Value=UxTheme.dll
> Sig[4].Name=Fault Module Version
> Sig[4].Value=10.0.14393.0
> Sig[5].Name=Fault Module Timestamp
> Sig[5].Value=57899875
> Sig[6].Name=Exception Code
> Sig[6].Value=c0000005
> Sig[7].Name=Exception Offset
> Sig[7].Value=0000000000021864
> DynamicSig[1].Name=OS Version
> DynamicSig[1].Value=10.0.14393.2.0.0.768.101
> DynamicSig[2].Name=Locale ID
> DynamicSig[2].Value=1031
> DynamicSig[22].Name=Additional Information 1
> DynamicSig[22].Value=b948
> DynamicSig[23].Name=Additional Information 2
> DynamicSig[23].Value=b948905464a74d559d8c356ce8270e15
> DynamicSig[24].Name=Additional Information 3
> DynamicSig[24].Value=e82c
> DynamicSig[25].Name=Additional Information 4
> DynamicSig[25].Value=e82cc05b722a5532f382cea4cb3fdc84
> UI[2]=C:\WINDOWS\system32\winlogon.exe
> UI[5]=Check online for a solution (recommended)
> UI[6]=Check for a solution later (recommended)
> UI[7]=Close
> UI[8]=Windows Logon Application stopped working and was closed
> UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
> UI[10]=&Close
> LoadedModule[0]=C:\WINDOWS\system32\winlogon.exe
> LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
> LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
> LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
> LoadedModule[4]=C:\WINDOWS\System32\msvcrt.dll
> LoadedModule[5]=C:\WINDOWS\System32\sechost.dll
> LoadedModule[6]=C:\WINDOWS\System32\RPCRT4.dll
> LoadedModule[7]=C:\WINDOWS\System32\powrprof.dll
> LoadedModule[8]=C:\WINDOWS\System32\ucrtbase.dll
> LoadedModule[9]=C:\WINDOWS\System32\advapi32.dll
> LoadedModule[10]=C:\WINDOWS\system32\bcrypt.dll
> LoadedModule[11]=C:\WINDOWS\System32\profapi.dll
> LoadedModule[12]=C:\WINDOWS\SYSTEM32\winsta.dll
> LoadedModule[13]=C:\WINDOWS\System32\user32.dll
> LoadedModule[14]=C:\WINDOWS\System32\win32u.dll
> LoadedModule[15]=C:\WINDOWS\System32\GDI32.dll
> LoadedModule[16]=C:\WINDOWS\System32\gdi32full.dll
> LoadedModule[17]=C:\WINDOWS\System32\IMM32.DLL
> LoadedModule[18]=C:\WINDOWS\system32\UXINIT.dll
> LoadedModule[19]=C:\WINDOWS\System32\shcore.dll
> LoadedModule[20]=C:\WINDOWS\System32\combase.dll
> LoadedModule[21]=C:\WINDOWS\System32\bcryptPrimitives.dll
> LoadedModule[22]=C:\WINDOWS\system32\UxTheme.dll
> LoadedModule[23]=C:\WINDOWS\System32\CRYPT32.dll
> LoadedModule[24]=C:\WINDOWS\System32\MSASN1.dll
> LoadedModule[25]=C:\WINDOWS\system32\DPAPI.dll
> LoadedModule[26]=C:\WINDOWS\system32\CRYPTBASE.dll
> LoadedModule[27]=C:\WINDOWS\SYSTEM32\dwminit.dll
> LoadedModule[28]=C:\WINDOWS\system32\SspiCli.dll
> LoadedModule[29]=C:\WINDOWS\system32\apphelp.dll
> LoadedModule[30]=C:\WINDOWS\SYSTEM32\usermgrcli.dll
> LoadedModule[31]=C:\WINDOWS\SYSTEM32\ntmarta.dll
> LoadedModule[32]=C:\WINDOWS\system32\CRYPTSP.dll
> LoadedModule[33]=C:\WINDOWS\system32\rsaenh.dll
> State[0].Key=Transport.DoneStage1
> State[0].Value=1
> FriendlyEventName=Stopped working
> ConsentKey=APPCRASH
> AppName=Windows Logon Application
> AppPath=C:\WINDOWS\system32\winlogon.exe
> NsPartner=windows
> NsGroup=windows8
> ApplicationIdentity=4DDBF371EB8F8B25A2AC000ADA5E5BDA
> MetadataHash=-1018524646
> 
> Version=1
> EventType=APPCRASH
> EventTime=131169649064377674
> ReportType=2
> Consent=1
> UploadTime=131170513676405615
> ReportIdentifier=0f70e21e-6e0d-11e6-9c6b-d9f3f921b2ef
> IntegratorReportIdentifier=0ab0a46e-c701-4b47-a01f-2bac81083559
> NsAppName=dwm.exe
> AppSessionGuid=0000297c-0003-0010-6a1d-e6ce1902d201
> TargetAppId=W:0000da39a3ee5e6b4b0d3255bfef95601890afd80709!0000da39a3ee5e6b4b0d3255bfef95601890afd80709!dwm.exe
> TargetAppVer=1970//01//01:00:00:00!0!dwm.exe
> BootId=4294967295
> Response.type=4
> Sig[0].Name=Application Name
> Sig[0].Value=dwm.exe
> Sig[1].Name=Application Version
> Sig[1].Value=10.0.14393.0
> Sig[2].Name=Application Timestamp
> Sig[2].Value=578999ab
> Sig[3].Name=Fault Module Name
> Sig[3].Value=udwm.dll
> Sig[4].Name=Fault Module Version
> Sig[4].Value=10.0.14393.0
> Sig[5].Name=Fault Module Timestamp
> Sig[5].Value=5789987f
> Sig[6].Name=Exception Code
> Sig[6].Value=c00001ad
> Sig[7].Name=Exception Offset
> Sig[7].Value=000000000009b076
> DynamicSig[1].Name=OS Version
> DynamicSig[1].Value=10.0.14393.2.0.0.768.101
> DynamicSig[2].Name=Locale ID
> DynamicSig[2].Value=1031
> UI[2]=C:\WINDOWS\system32\dwm.exe
> UI[5]=Check online for a solution (recommended)
> UI[6]=Check for a solution later (recommended)
> UI[7]=Close
> UI[8]=Desktop Window Manager stopped working and was closed
> UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
> UI[10]=&Close
> State[0].Key=Transport.DoneStage1
> State[0].Value=1
> FriendlyEventName=Stopped working
> ConsentKey=APPCRASH
> AppName=Desktop Window Manager
> AppPath=C:\WINDOWS\system32\dwm.exe
> NsPartner=windows
> NsGroup=windows8
> ApplicationIdentity=A043C694A1C61AED3F76F30C3ED5B493
> MetadataHash=674977508

**Comment by riverar** [comment]
Closing due to age, please file a new issue if needed.
