### ISSUE TITLE
Latest release failed to install on Windows 7 SP1 x64 [UxStyle_0242_x86_x64_preview]

### ISSUE THREAD

**Issue by RadarNyan** [riverar/uxstyle#36]
Logs attached:
[UxStyle_20160930191302.log](https://github.com/riverar/uxstyle/files/502662/UxStyle_20160930191302.txt)
[UxStyle_20160930191302_0_Installer64.log](https://github.com/riverar/uxstyle/files/502663/UxStyle_20160930191302_0_Installer64.txt)

**Comment by riverar** [comment]
Closing due to age, file a new issue if needed please.
