### ISSUE TITLE
UxStyle_0242_x86_x64_preview (Windows 10 Build 9926 x64)

### ISSUE THREAD

**Issue by daveo76** [riverar/uxstyle#5]
This time it works but after restarting or power on it causes explorer.exe not to work properly. I have to select Windows default theme to make explorer.exe work again then select the theme I want. The 2 themes I tried was 
http://link6155.deviantart.com/art/Silk-for-Windows-10-Technical-Preview-487071428
http://damonkeyoncrack.deviantart.com/art/Aero7-V2-for-Windows-8-8-1-10-TP-429412929
Is there a log file somewhere I can provide to you

**Comment by riverar** [comment]
Doesn't look like a UxStyle problem. Looks like stylebuilder isn't outputting valid files for Windows 10 JTP. Please report the issue here: http://www.vistastylebuilder.com/forum/

**Comment by daveo76** [comment]
Thanks I put up with it as it is. That link seems it for theme makers.
