### ISSUE TITLE
UxStyle_0242_x86_x64_preview (Windows 10 Build 10036 x64)

### ISSUE THREAD

**Issue by daveo76** [riverar/uxstyle#7]
No issue. I wanted to let you know that UxStyle_0242_x86_x64_preview works better on the new leaked build. I'm able to boot on to Windows now with no problem. Also I'm still using the same theme to

**Comment by angerthosenear** [comment]
Does the new build allow you to boot without getting stuck on a blackscreen on boot? I had to manually reset the style path when that happened.

**Comment by daveo76** [comment]
Yes it allows you to boot without getting stuck on a blackscreen

**Comment by angerthosenear** [comment]
Woo!!

Can confirm no more blackscreen on boot. Probably my theme I'm trying to use (Silk), but most of the things are invisible - start menu, fly out menus, any of the metro stuff. The search bar persists. And the taskbar icons are rather wide. I would take a screenie, but the search bar is in the way lol....
