### ISSUE TITLE
Virtualbox trubles with patched uxtheme

### ISSUE THREAD

**Issue by blackcrack** [riverar/uxstyle#8]
Hi,

there gives an couble problems with Virtualbox..
is this directly an want problem or it's this an problem from different uxpach-programms ?

https://www.google.de/?gfe_rd=cr&ei=JTEMVdiPJ6KI8Qf814DgCw&gws_rd=ssl#q=virtualbox+uxtheme+problems

**Comment by riverar** [comment]
Unrelated to UxStyle. Should have no problem using on VirtualBox.
